export const SET_LESSONS = 'SET_LESSONS';
export const SET_ADDITIONAL_PROPS = 'SET_ADDITIONAL_PROPS';
export const SET_IS_TRANSFERRED_TO_CANVAS = 'SET_IS_TRANSFERRED_TO_CANVAS';
export const SET_USERS_FROM_CANVAS = 'SET_USERS_FROM_CANVAS';